-- migrate:up
CREATE TABLE users(
  id INT NOT NULL AUTO_INCREMENT,
  kakao_id BIGINT UNIQUE KEY NULL,
  name VARCHAR(50) NULL,
  email VARCHAR(100) NULL,
  password VARCHAR(100) NULL,
  phone_number VARCHAR(100) NULL UNIQUE KEY,
  point DECIMAL (10,2) NULL DEFAULT 1000000,
  create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
-- migrate:down
DROP TABLE users;